---

- name: issues with traffic being routed incorrectly due to iptables being bypassed
  shell: |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sysctl --system
  args:
    executable: /bin/bash

- name: Add the dummy module
  modprobe:
    name: br_netfilter
    state: present

- name: Add k8s repo
  shell: |
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOF
  args:
    executable: /bin/bash

- name: Set SELinux in permissive mode (effectively disabling it)
  shell: |
    setenforce 0
    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  args:
    executable: /bin/bash

- name: Install packages
  yum:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: latest
    disable_excludes: all
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Start kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes
  become: yes
